#ifndef __WINDOW_PROPERTIES_H__
#define __WINDOW_PROPERTIES_H__

const int WINDOW_MAX_X = 600;
const int WINDOW_MAX_Y = 600;
const int WINDOW_POSITION_X = 100;
const int WINDOW_POSITION_Y = 100;
const int WORLD_COORDINATE_MIN_X = -300;
const int WORLD_COORDINATE_MIN_Y = -300;
const int WORLD_COORDINATE_MAX_X = 300;
const int WORLD_COORDINATE_MAX_Y = 300;

#endif